### ISSUE TITLE
Error inject all asset to html using replaceAssetsInHtml

### ISSUE THREAD

**Issue by restuwahyu13** [toxic-johann/webpack-cdn-upload-plugin#59]
(node:1916) UnhandledPromiseRejectionWarning: TypeError: Expected a string
    at module.exports (C:\Users\Anti-Malware\Desktop\dummy\node_modules\webpack-cdn-upload-plugin\node_modules\escape-string-regexp\index.js:5:9)
    at WebpackCdnUploadPlugin.<anonymous> (C:\Users\Anti-Malware\Desktop\dummy\node_modules\webpack-cdn-upload-plugin\lib\index.js:100:68)
    at Generator.next (<anonymous>)
    at C:\Users\Anti-Malware\Desktop\dummy\node_modules\webpack-cdn-upload-plugin\lib\index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Anti-Malware\Desktop\dummy\node_modules\webpack-cdn-upload-plugin\lib\index.js:4:12)
    at afterHtmlProcessFn (C:\Users\Anti-Malware\Desktop\dummy\node_modules\webpack-cdn-upload-plugin\lib\index.js:95:70)
    at eval (eval at create (C:\Users\Anti-Malware\Desktop\dummy\node_modules\tapable\lib\HookCodeFactory.js:74:10), <anonymous>:15:1)
    at new Promise (<anonymous>)
    at AsyncSeriesWaterfallHook.eval [as promise] (eval at create (C:\Users\Anti-Malware\Desktop\dummy\node_modules\tapable\lib\HookCodeFactory.js:74:10), <anonymous>:4:8)
    at AsyncSeriesWaterfallHook.lazyCompileHook (C:\Users\Anti-Malware\Desktop\dummy\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\Anti-Malware\Desktop\dummy\node_modules\html-webpack-plugin\index.js:254:70
(node:1916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1916) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by toxic-johann** [comment]
Can you provide some code sample to reproduce this?

**Comment by toxic-johann** [comment]
Close this for no response.
